server:
  port: 80

spring:
  thymeleaf:
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

  # 热部署生效
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      #      classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**

  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/qingchun?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true

#mybatis-plus 映射的mapper.xml,以及实体类名
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zr.qingchun.model


#自定义阿里云支付配置
alipay:
  app_id: 2016092100564324
  #商户私钥
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCaVARNjCP3qeFp50F0vCirx38ehY9HyoVBrcKZCYCtsVKwpmVcOY7OunPZdhXf7CuerqCedPDDZlx6UL39MAqFmF+4RU2kBhkEvmO/Z7V8NeC6lmuNG/M8eukIq9NzWIicyBgujizqrXT2aM5GmmIHxzAIABeaNDyNCF7g7tKPeN38aH5wKmKgg2CuC57VqtKG/puzZcsC1rV5b00gLHYXid2W9z5idW0UYJPESbMR5pyJMgx1zxwwl+8VqMnTxvyLv96MKahkYS901xLEBOiNp0xdjx93H++cHOIY2yClWOhISY/Go4TYzxe9CsTrOffCNbmps8Z57qFlLkzFAZMNAgMBAAECggEAdkfQaHLxGh88oYNZepO/hDDJb+Yjc313dmgrjklnMziFzNgrNWzz0+O5aMEFcPK8V8k1V1z/LnOkiyaZBpUsa0nmiv+qyvzVbfpRzuA4i3NrwvYIhkUWvpLhSgEPdgcz5R3C0uOq7050J2saNaibW6TBXlBbxpcklV8GANVp0gU49A13eRKPapoNIYVTC3VkpaIFbFRE6OoVipF7zDvgq5+hZAG9Hp5nIE59tScefocjPrEs7OIWDs7vuXpLCczwJJW1E5/QV4yZyKlqsBhdsO2drwZcfGcfuWnEyv3REFcE2lwFfK13ZskFuCSQuPRT06xprP+nVXinlJ/ZZSWL4QKBgQDg4vySskg1jsyTfCj91vBtgppf+vwXXIFrL4fgR1LF9ilk1fEcUcBXd5a5l2sFJEriQdl6lb95Pfs1kotMSEh4u8NTy/OXh8x7FjdtpnTq9fQ42kBq3Oe8bhp2swmCvnyt9wEnzVbLyclOvnZEYyqUv9uJVo/zNu94KAqXONnuNQKBgQCvrf9HIIytWJx9JiFLZIbJCfbAb38ge5pSdI7MK9nfOd1gGnMB2PPOINMOhlzo/XIMYGOI4RxmGrZ1xoYD3zZGcODnkHn5UX5O44SXE6D5R4CGQsnjmuEFXPZioKq0G21AkGfT7C0RMFUKag/h9N+cny4pfPDobr3L02wkjC+MeQKBgFZwKLCiAgtD9fICWScoRIVzG68ko1y/W6c9P7a+81vPwB1X9jLyYUG9X5u6TZJOXtIUiWkKwevyHOp8hzos1l5BnVRKIjjuI3R0F533yxy8qMBpczUf75qHn3hcXJ16ZiXfuPv5exEdYFj58C9dBnLiQ5nIQdA0H1tJ2LhDS9C5AoGBAIoQA/6x5dyVNuZjgObvKb30xqaU+SNd//mtAEwUajS0FPXh02AwT+o+gZ94mKvCAk8XsSFxSBA2Dg6g5dFFKjJRo25YbIMzOEBnLVxNYMSHHMpm0qK8pPrCBB+ehIjmxQVodzBk+0X25d45XCIHf3Rm5LBWMD16Sk5U6TgPs46BAoGAIUciOigYNQJ3FQNsVYdHFvy5FB83yzGCYVoG/02F6MB2v4Bvd4/9PM/cLwsEF7//T9UVjnsfFEdpupFq649Q3/4JPEDNIFn5nZN056sDm0bLQfTbxSF52m6Z1Rtk7ID03j127kMaXKiUcf4t6mknBF2ENnUpBQjMeiwqctSF4hg=
  #支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApBVZeWSspKCnQRVHt9QBNs+o544zlB1NOXP2CtFJuwOmmst/ngBbT3M+PrsqmUvvVn+T8+JHN/gDugRjn/9DX7sLLh5a0bQiLGIR3uXCavbcBb6eCrKEhzlwhjyX05HAqe8IUYUEUiMWbKy/LbOzAEsVB0RHCTdrkG4Oe73ypWOseTPMpzcfEzt7vZBy/MRbhksuN5b+9htgKHIJXMQ+g+9mADWBveECAW2CpeANYQQIjyzzKptuVeQUfQToC5C155geqdIg/k1KINnf+im3uLxOmW0poRVsUyNCxcPfXK9CE0rsUtYeiWqBh7giPQf8FbRZiXl6HxUrPeCCi2JAIQIDAQAB
  #异步通知返回路径
  notify_url: http://f7cfa8bd.ngrok.io/alipay/notifyUrl
  #同步返回页面的url
  return_url: http://f7cfa8bd.ngrok.io/alipay/returnUrl
  #延签方式
  sign_type: RSA2
  #字符编码
  charset: utf-8
  #支付宝网关
  gatewayUrl: https://openapi.alipaydev.com/gateway.do

#微信配置
wx:
  appid:
  mch_id:
  key:
  notify_url: http://www.baidu.com


#微信接口API
wxapi:
  #native支付统一下单接口
  unifieorderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
  #获取行业信息
  getInsustryUrl: https://api.weixin.qq.com/cgi-bin/template/get_industry
  #发送模板信息
  sendTemplateUrl: https://api.weixin.qq.com/cgi-bin/message/template/send
  #创建行业模板
  apiSetIndustryUrl: https://api.weixin.qq.com/cgi-bin/template/api_set_industry
  #获得模板id
  apiAddTemplateUrl: https://api.weixin.qq.com/cgi-bin/template/api_add_template
  #通过模板id 删除模板
  delPrivateTemplateUrl: https://api.weixin.qq.com/cgi-bin/template/del_private_template
  #获取模板列表
  getAllPrivateTemplateUrl: https://api.weixin.qq.com/cgi-bin/template/get_all_private_template



